source 'https://rubygems.org'

##### Rails #####
gem 'rails', '4.0.2'

##### DB #####
gem 'sqlite3'
gem 'mysql2', '~> 0.3.15'

##### Stylesheets #####
gem 'turbolinks'
gem 'sass-rails', '~> 4.0.0'
gem 'therubyracer', '~> 0.12.1'

##### Javascripts and JQuery #####
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

##### JSON #####
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end